# Generated by Django 2.2.7 on 2019-11-24 18:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timers', '0002_auto_20191119_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimerStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timers.Timer')),
            ],
        ),
        migrations.CreateModel(
            name='TimerStart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timers.Timer')),
            ],
        ),
    ]
